apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-k8s-player
  labels:
    deploy: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: sam-spring-app
        image: myguddy/sam-k8s-player
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: spring-properties
              key: active-profile
        ports:
        - name: tomcat
          containerPort: 8080
        volumeMounts:
        - name: spring-properties
          mountPath: /config
      volumes:
      - name: spring-properties
        configMap:
          name: spring-properties
        